version: '2'
services:
    judgehost:
        build: ./judgehost
        hostname: judgehost01
        privileged: true
        environment:
            - DOMSERVER_HOST=https://chipcie.ch.tudelft.nl/api
            - DOMSERVER_PASSWORD=password
