version: '3'
services:
    judgehost:
        build: ./judgehost
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        privileged: true
        env_file:
            - judgehost.env
